FROM node:20-alpine

ENV NODE_ENV production

RUN apk update && apk upgrade && apk add bash

SHELL ["/bin/bash", "-c"]

WORKDIR /app

COPY \
  package.json ./ \
  pnpm-lock.yaml ./ \
  tsconfig.json ./ \
  tsconfig.build.json ./ \
  .env ./ \
  topic.json ./ \
  swagger-description*.md ./ \
  nest-cli.json ./

RUN npm install --global pnpm \
    && SHELL=bash pnpm setup \
    && source /root/.bashrc

ENV PNPM_HOME=/usr/local/bin

COPY src /app/src

RUN pnpm install --frozen-lockfile && pnpm build

CMD ["pnpm", "start:prod"]
